project_id = "hviqoaokxvlancmftwuo"

[functions.docusign-webhook]
verify_jwt = false

[functions.veriff-webhook]
verify_jwt = false

[functions.customer-chat]
verify_jwt = false

[functions.validate-customer-invite]
verify_jwt = false

[functions.submit-customer-registration]
verify_jwt = false

[functions.custom-auth-email]
verify_jwt = false

[functions.subscription-webhook]
verify_jwt = false

[functions.stripe-webhook-test]
verify_jwt = false

[functions.stripe-webhook-live]
verify_jwt = false